@tool
extends RefCounted
class_name FSMGenerator

static func generate_fsm(
	script_name: String,
	base_class: String,
	state_nodes: Array,
	connections: Array,
	enemy_scene_path: String,
	player_scene_path: String,
	anim_player_path: String
):
	var dir_path = "res://ai_states/" + script_name + "/"
	var dir = DirAccess.open("res://")
	
	if not dir.dir_exists(dir_path):
		dir.make_dir_recursive(dir_path)
	
	print("📁 Output directory: ", dir_path)
	
	# Find initial state
	var initial_state = null
	for node in state_nodes:
		if node.is_initial_state():
			initial_state = node
			break
	
	if not initial_state and state_nodes.size() > 0:
		initial_state = state_nodes[0]
	
	# Generate main FSM controller
	_generate_main_fsm(dir_path, script_name, base_class, state_nodes, initial_state, anim_player_path)
	
	# Generate individual state scripts
	for node in state_nodes:
		_generate_state_script(dir_path, node, state_nodes, connections)
	
	# Generate base state class
	_generate_base_state(dir_path)
	
	# Generate helper utilities
	_generate_blackboard(dir_path)
	
	print("✓ All scripts generated successfully!")

static func _generate_main_fsm(
	dir_path: String,
	script_name: String,
	base_class: String,
	state_nodes: Array,
	initial_state,
	anim_player_path: String
):
	var code = ""
	
	# Header
	code += "# Auto-generated FSM Controller\n"
	code += "# Generated by OmniState Visual AI Plugin\n"
	code += "# DO NOT EDIT MANUALLY - Changes will be overwritten\n\n"
	
	code += "extends " + base_class + "\n"
	code += "class_name " + _to_pascal_case(script_name) + "\n\n"
	
	# Properties
	code += "# FSM Components\n"
	code += "@onready var animation_player: AnimationPlayer = $" + anim_player_path + "\n"
	code += "@onready var blackboard: Blackboard = Blackboard.new()\n\n"
	
	code += "# State Management\n"
	code += "var current_state: State = null\n"
	code += "var states: Dictionary = {}\n"
	code += "var state_history: Array[String] = []\n\n"
	
	code += "# References\n"
	code += "var player: Node = null\n"
	code += "var navigation_agent: NavigationAgent3D = null\n\n"
	
	# Ready function
	code += "func _ready():\n"
	code += "\t# Initialize blackboard\n"
	code += "\tadd_child(blackboard)\n"
	code += "\tblackboard.set_value(\"owner\", self)\n\n"
	
	code += "\t# Find player\n"
	code += "\tplayer = get_tree().get_first_node_in_group(\"player\")\n"
	code += "\tif player:\n"
	code += "\t\tblackboard.set_value(\"player\", player)\n\n"
	
	code += "\t# Setup navigation\n"
	code += "\tnavigation_agent = get_node_or_null(\"NavigationAgent3D\")\n"
	code += "\tif navigation_agent:\n"
	code += "\t\tblackboard.set_value(\"navigation_agent\", navigation_agent)\n\n"
	
	code += "\t# Initialize states\n"
	code += "\t_initialize_states()\n\n"
	
	code += "\t# Start with initial state\n"
	if initial_state:
		code += "\tchange_state(\"" + initial_state.get_state_name() + "\")\n\n"
	else:
		code += "\t# No initial state defined\n\n"
	
	# Initialize states function
	code += "func _initialize_states():\n"
	for node in state_nodes:
		var state_name = node.get_state_name()
		var state_class = _to_pascal_case(state_name) + "State"
		code += "\tstates[\"" + state_name + "\"] = " + state_class + ".new()\n"
		code += "\tstates[\"" + state_name + "\"].state_machine = self\n"
		code += "\tstates[\"" + state_name + "\"].blackboard = blackboard\n"
	code += "\n"
	
	# Physics process
	code += "func _physics_process(delta: float):\n"
	code += "\tif current_state:\n"
	code += "\t\tcurrent_state.update(delta)\n"
	code += "\t\t_check_transitions()\n\n"
	
	# Change state function
	code += "func change_state(new_state_name: String):\n"
	code += "\tif not states.has(new_state_name):\n"
	code += "\t\tpush_error(\"State not found: \" + new_state_name)\n"
	code += "\t\treturn\n\n"
	code += "\tif current_state:\n"
	code += "\t\tstate_history.append(current_state.get_state_name())\n"
	code += "\t\tcurrent_state.exit()\n\n"
	code += "\tcurrent_state = states[new_state_name]\n"
	code += "\tcurrent_state.enter()\n"
	code += "\tprint(\"[FSM] Changed to state: \", new_state_name)\n\n"
	
	# Check transitions
	code += "func _check_transitions():\n"
	code += "\tif not current_state:\n"
	code += "\t\treturn\n\n"
	code += "\tvar now = Time.get_ticks_msec() / 1000.0\n"
	code += "\tvar transitions = current_state.get_transitions()\n"
	code += "\t# Sort by priority (lower number = higher priority)\n"
	code += "\ttransitions.sort_custom(func(a, b): return a.get(\"priority\", 10) < b.get(\"priority\", 10))\n"
	code += "\tfor transition in transitions:\n"
	code += "\t\t# Cooldown check\n"
	code += "\t\tvar cooldown_key = \"_cd_\" + transition.to_state\n"
	code += "\t\tvar last_fire = blackboard.get_value(cooldown_key) if blackboard.has_value(cooldown_key) else 0.0\n"
	code += "\t\tvar cooldown = transition.get(\"cooldown\", 0.0)\n"
	code += "\t\tif cooldown > 0.0 and now - last_fire < cooldown:\n"
	code += "\t\t\tcontinue\n"
	code += "\t\tif _evaluate_condition(transition.condition):\n"
	code += "\t\t\t# Delay check\n"
	code += "\t\t\tvar delay = transition.get(\"delay\", 0.0)\n"
	code += "\t\t\tvar delay_key = \"_delay_\" + transition.to_state\n"
	code += "\t\t\tif delay > 0.0:\n"
	code += "\t\t\t\tif not blackboard.has_value(delay_key):\n"
	code += "\t\t\t\t\tblackboard.set_value(delay_key, now)\n"
	code += "\t\t\t\t\tcontinue\n"
	code += "\t\t\t\telif now - blackboard.get_value(delay_key) < delay:\n"
	code += "\t\t\t\t\tcontinue\n"
	code += "\t\t\t# Fire transition\n"
	code += "\t\t\tblackboard.set_value(cooldown_key, now)\n"
	code += "\t\t\tif blackboard.has_value(delay_key):\n"
	code += "\t\t\t\tblackboard.set_value(delay_key, null)\n"
	code += "\t\t\t# Custom code on transition\n"
	code += "\t\t\tvar custom = transition.get(\"custom_code\", \"\")\n"
	code += "\t\t\tif custom != \"\":\n"
	code += "\t\t\t\tvar expr = Expression.new()\n"
	code += "\t\t\t\tif expr.parse(custom) == OK:\n"
	code += "\t\t\t\t\texpr.execute([], self)\n"
	code += "\t\t\t# Debug log\n"
	code += "\t\t\tif transition.get(\"debug_log\", false):\n"
	code += "\t\t\t\tvar lbl = transition.get(\"debug_label\", \"\")\n"
	code += "\t\t\t\tprint(\"[FSM] \", lbl if lbl != \"\" else (get_current_state_name() + \" → \" + transition.to_state))\n"
	code += "\t\t\tchange_state(transition.to_state)\n"
	code += "\t\t\tbreak\n"
	code += "\t\telse:\n"
	code += "\t\t\t# Reset delay timer if condition is no longer true\n"
	code += "\t\t\tvar delay_key = \"_delay_\" + transition.to_state\n"
	code += "\t\t\tif blackboard.has_value(delay_key):\n"
	code += "\t\t\t\tblackboard.set_value(delay_key, null)\n\n"
	
	# Evaluate condition
	code += "func _evaluate_condition(condition: String) -> bool:\n"
	code += "\t# Simple condition evaluation\n"
	code += "\t# You can extend this with more complex logic\n"
	code += "\tif condition == \"\":\n"
	code += "\t\treturn false\n\n"
	code += "\t# Check blackboard values\n"
	code += "\tif blackboard.has_value(condition):\n"
	code += "\t\treturn blackboard.get_value(condition)\n\n"
	code += "\t# Try to evaluate as expression\n"
	code += "\tvar expression = Expression.new()\n"
	code += "\tvar error = expression.parse(condition)\n"
	code += "\tif error == OK:\n"
	code += "\t\tvar result = expression.execute([], self)\n"
	code += "\t\tif not expression.has_execute_failed():\n"
	code += "\t\t\treturn result\n\n"
	code += "\treturn false\n\n"
	
	# Helper functions
	code += "# Helper Functions\n"
	code += "func get_current_state_name() -> String:\n"
	code += "\treturn current_state.get_state_name() if current_state else \"\"\n\n"
	
	code += "func get_previous_state() -> String:\n"
	code += "\treturn state_history[-1] if state_history.size() > 0 else \"\"\n\n"
	
	code += "func force_state(state_name: String):\n"
	code += "\tchange_state(state_name)\n\n"
	
	# Save file
	var file = FileAccess.open(dir_path + script_name + ".gd", FileAccess.WRITE)
	file.store_string(code)
	file.close()
	
	print("✓ Generated main FSM: ", script_name + ".gd")

static func _generate_state_script(dir_path: String, node, all_nodes: Array, connections: Array):
	var state_name = node.get_state_name()
	var file_name = state_name.to_snake_case() + "_state.gd"
	var file_path = dir_path + file_name
	
	# Check if file already exists
	var existing_file_content = ""
	var file_exists = FileAccess.file_exists(file_path)
	
	if file_exists:
		var existing_file = FileAccess.open(file_path, FileAccess.READ)
		if existing_file:
			existing_file_content = existing_file.get_as_text()
			existing_file.close()
	
	var code = ""
	
	# Header
	code += "# State: " + state_name + "\n"
	code += "# Auto-generated by OmniState Visual AI Plugin\n"
	code += "#\n"
	code += "# ✅ SAFE TO EDIT:\n"
	code += "# • Add custom functions - they will be preserved\n"
	code += "# • Add custom properties - they will be preserved\n"
	code += "# • Edit enter/update/exit in visual editor, not here\n"
	code += "#\n"
	code += "# ⚠️ REGENERATED ON SAVE:\n"
	code += "# • enter(), update(), exit() functions\n"
	code += "# • get_state_name(), get_transitions()\n"
	code += "# • ANIMATION_NAME constant\n"
	code += "\n"
	
	code += "extends State\n"
	code += "class_name " + _to_pascal_case(state_name) + "State\n\n"
	
	# Extract custom properties from existing file (if any)
	var custom_properties = ""
	if file_exists:
		custom_properties = _extract_custom_properties(existing_file_content)
	
	# Properties
	var anim_name = node.get_selected_animation()
	var is_dynamic_anim = node.is_dynamic_animation()
	
	if anim_name != "" and not is_dynamic_anim:
		code += "const ANIMATION_NAME = \"" + anim_name + "\"\n\n"
	
	# Add custom properties if found
	if custom_properties != "":
		code += "# Custom Properties\n"
		code += custom_properties + "\n\n"
	
	# Get state name
	code += "func get_state_name() -> String:\n"
	code += "\treturn \"" + state_name + "\"\n\n"
	
	# Get transitions
	code += "func get_transitions() -> Array:\n"
	code += "\treturn [\n"
	for trans in node.transitions:
		var priority = trans.get("priority", 10)
		var delay = trans.get("delay", 0.0)
		var cooldown = trans.get("cooldown", 0.0)
		var can_interrupt = trans.get("can_interrupt", true)
		var blend_time = trans.get("blend_time", 0.0)
		var custom_code = trans.get("custom_code", "").replace("\"", "\\\"").replace("\n", "\\n")
		var debug_log = trans.get("debug_log", false)
		var debug_label = trans.get("debug_label", "").replace("\"", "\\\"")
		code += "\t\t{\"to_state\": \"" + trans.to_state + "\", \"condition\": \"" + trans.condition + "\""
		code += ", \"priority\": " + str(priority)
		code += ", \"delay\": " + str(delay)
		code += ", \"cooldown\": " + str(cooldown)
		code += ", \"can_interrupt\": " + str(can_interrupt).to_lower()
		code += ", \"blend_time\": " + str(blend_time)
		code += ", \"custom_code\": \"" + custom_code + "\""
		code += ", \"debug_log\": " + str(debug_log).to_lower()
		code += ", \"debug_label\": \"" + debug_label + "\""
		code += "},\n"
	code += "\t]\n\n"
	
	# Enter function
	code += "func enter():\n"
	
	# Only add automatic animation playing if NOT dynamic
	if anim_name != "" and not is_dynamic_anim:
		code += "\tif state_machine.animation_player:\n"
		code += "\t\tstate_machine.animation_player.play(ANIMATION_NAME)\n\n"
	
	var enter_code = node.enter_code_input.text.strip_edges()
	if enter_code != "" and enter_code != "# Enter state logic\npass" and enter_code != "pass":
		code += "\t# Custom enter logic\n"
		for line in enter_code.split("\n"):
			code += "\t" + line + "\n"
	else:
		code += "\tpass\n"
	code += "\n"
	
	# Update function
	code += "func update(delta: float):\n"
	var update_code = node.code_input.text.strip_edges()
	if update_code != "" and update_code != "# Update state logic\npass" and update_code != "pass":
		code += "\t# Custom update logic\n"
		for line in update_code.split("\n"):
			code += "\t" + line + "\n"
	else:
		code += "\tpass\n"
	code += "\n"
	
	# Exit function
	code += "func exit():\n"
	var exit_code = node.exit_code_input.text.strip_edges()
	if exit_code != "" and exit_code != "# Exit state logic\npass" and exit_code != "pass":
		code += "\t# Custom exit logic\n"
		for line in exit_code.split("\n"):
			code += "\t" + line + "\n"
	else:
		code += "\tpass\n"
	code += "\n"
	
	# Extract custom functions from existing file (if any)
	var custom_functions = ""
	if file_exists:
		custom_functions = _extract_custom_functions(existing_file_content)
	
	# Behavior functions (only add if not already in custom functions)
	if node.behaviors.size() > 0:
		code += "# Behavior Functions\n"
		for behavior in node.behaviors:
			# Check if this behavior already exists in custom functions
			if not custom_functions.contains("func " + behavior + "("):
				code += "func " + behavior + "() -> bool:\n"
				code += "\t# TODO: Implement " + behavior + " logic\n"
				code += "\treturn false\n\n"
	
	# Add custom functions at the end
	if custom_functions != "":
		code += "# Custom Functions (preserved from previous generation)\n"
		code += custom_functions + "\n"
	
	# Save file
	var file = FileAccess.open(file_path, FileAccess.WRITE)
	file.store_string(code)
	file.close()
	
	if file_exists:
		print("✓ Updated state (preserved custom code): ", file_name)
	else:
		print("✓ Generated state: ", file_name)

static func _extract_custom_properties(file_content: String) -> String:
	"""Extract custom variable declarations between class_name and first func"""
	var lines = file_content.split("\n")
	var custom_props = []
	var in_custom_section = false
	var found_class_name = false
	
	for line in lines:
		# Start collecting after class_name line
		if line.strip_edges().begins_with("class_name "):
			found_class_name = true
			continue
		
		# Stop at first function or known sections
		if found_class_name and (line.strip_edges().begins_with("func ") or 
		   line.strip_edges().begins_with("# Behavior Functions") or
		   line.strip_edges().begins_with("# Custom Functions")):
			break
		
		# Skip known generated content
		if found_class_name and (line.strip_edges().begins_with("const ANIMATION_NAME") or
		   line.strip_edges().begins_with("# Custom Properties")):
			continue
		
		# Collect custom properties (var, const, @export, etc.)
		if found_class_name and line.strip_edges() != "":
			if (line.strip_edges().begins_with("var ") or 
			    line.strip_edges().begins_with("const ") or
			    line.strip_edges().begins_with("@export") or
			    line.strip_edges().begins_with("@onready")):
				custom_props.append(line)
	
	return "\n".join(custom_props)

static func _extract_custom_functions(file_content: String) -> String:
	"""Extract custom functions that are not enter/update/exit/get_state_name/get_transitions"""
	var lines = file_content.split("\n")
	var custom_funcs = []
	var current_func = []
	var in_custom_func = false
	var func_indent = 0
	
	var standard_funcs = ["func get_state_name(", "func get_transitions(", "func enter(", "func update(", "func exit("]
	
	for i in range(lines.size()):
		var line = lines[i]
		
		# Check if this is a function declaration
		if line.strip_edges().begins_with("func "):
			# Check if it's a standard function
			var is_standard = false
			for std_func in standard_funcs:
				if line.strip_edges().begins_with(std_func):
					is_standard = true
					break
			
			# If we were in a custom function, save it
			if in_custom_func and current_func.size() > 0:
				custom_funcs.append("\n".join(current_func))
				current_func = []
			
			# Start new custom function if not standard
			if not is_standard:
				in_custom_func = true
				current_func.append(line)
				# Detect indentation
				func_indent = 0
				for c in line:
					if c == '\t':
						func_indent += 1
					else:
						break
			else:
				in_custom_func = false
		
		# If in custom function, collect lines
		elif in_custom_func:
			# Check if we've left the function (less indentation and not empty)
			if line.strip_edges() != "":
				var current_indent = 0
				for c in line:
					if c == '\t':
						current_indent += 1
					else:
						break
				
				# If back to class level (indent 0) and not a comment, stop
				if current_indent == 0 and not line.strip_edges().begins_with("#"):
					if current_func.size() > 0:
						custom_funcs.append("\n".join(current_func))
					current_func = []
					in_custom_func = false
					continue
			
			current_func.append(line)
	
	# Don't forget the last function
	if in_custom_func and current_func.size() > 0:
		custom_funcs.append("\n".join(current_func))
	
	return "\n\n".join(custom_funcs)

static func _generate_base_state(dir_path: String):
	var code = ""
	
	code += "# Base State Class\n"
	code += "# All states inherit from this\n\n"
	
	code += "extends RefCounted\n"
	code += "class_name State\n\n"
	
	code += "var state_machine = null\n"
	code += "var blackboard: Blackboard = null\n\n"
	
	code += "func get_state_name() -> String:\n"
	code += "\treturn \"base_state\"\n\n"
	
	code += "func get_transitions() -> Array:\n"
	code += "\treturn []\n\n"
	
	code += "func enter():\n"
	code += "\tpass\n\n"
	
	code += "func update(delta: float):\n"
	code += "\tpass\n\n"
	
	code += "func exit():\n"
	code += "\tpass\n\n"
	
	code += "# Helper functions\n"
	code += "func get_owner():\n"
	code += "\treturn blackboard.get_value(\"owner\") if blackboard else null\n\n"
	
	code += "func get_player():\n"
	code += "\treturn blackboard.get_value(\"player\") if blackboard else null\n\n"
	
	var file = FileAccess.open(dir_path + "state.gd", FileAccess.WRITE)
	file.store_string(code)
	file.close()
	
	print("✓ Generated base state class")

static func _generate_blackboard(dir_path: String):
	var code = ""
	
	code += "# Blackboard - Shared data storage for FSM\n"
	code += "# Used to share data between states\n\n"
	
	code += "extends Node\n"
	code += "class_name Blackboard\n\n"
	
	code += "var data: Dictionary = {}\n\n"
	
	code += "func set_value(key: String, value):\n"
	code += "\tdata[key] = value\n\n"
	
	code += "func get_value(key: String, default = null):\n"
	code += "\treturn data.get(key, default)\n\n"
	
	code += "func has_value(key: String) -> bool:\n"
	code += "\treturn data.has(key)\n\n"
	
	code += "func remove_value(key: String):\n"
	code += "\tdata.erase(key)\n\n"
	
	code += "func clear():\n"
	code += "\tdata.clear()\n\n"
	
	code += "func get_all_keys() -> Array:\n"
	code += "\treturn data.keys()\n\n"
	
	var file = FileAccess.open(dir_path + "blackboard.gd", FileAccess.WRITE)
	file.store_string(code)
	file.close()
	
	print("✓ Generated blackboard utility")

static func _to_pascal_case(text: String) -> String:
	var words = text.split("_")
	var result = ""
	for word in words:
		if word.length() > 0:
			result += word.capitalize()
	return result
